<?php

/**
 * @file
 * Implementations of installation hooks.
 */

/**
 * Implements hook_uninstall().
 */
function islandora_solrcloud_config_uninstall() {

  // Removing variables.
  $variables = array(
    'islandora_solrcloud_setting_delete','islandora_solrcloud_setting_uniqueid','islandora_solrcloud_setting_uniqueid_prefix'
  );
  foreach ($variables as $variable) {
    variable_del($variable);
  }
}
