<?xml version="1.0" encoding="UTF-8"?>

<!--
Self Transform for EML generated by CMODEL FORM. EML uses no prefix in elements inside <eml:eml>. But i Can´t get XLM_form_builder module to avoid default prefix at all. So i just generate the EML with root element
without prefix(eml:eml) and i add it here later. XML Form builder also removes schemaLocation for root node
We also get rid of the default namespace. Why? because it breaks EML to DC.
Diego Pino Navarro, April 2014
-->

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:dcterms="http://purl.org/dc/terms/"
	xmlns:eml="eml://ecoinformatics.org/eml-2.1.1"
	xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 http://rs.gbif.org/schema/eml-gbif-profile/1.0.2/eml.xsd">
	<xsl:output method="xml" indent="yes" omit-xml-declaration="yes" encoding="UTF-8"/>
	<xsl:template match="@* | node()">
		<xsl:copy>
			<xsl:apply-templates select="@* | node()"/>
		</xsl:copy>
	</xsl:template>
   
	<xsl:template match="/*">
      
		<xsl:element name="eml:{local-name()}">
			<xsl:copy-of select="namespace::dc" />
			<xsl:copy-of select="namespace::eml" />
			<xsl:copy-of select="namespace::proj" />
			<xsl:copy-of select="namespace::d" />
			<xsl:copy-of select="namespace::res" />
			<xsl:copy-of select="namespace::xsi" />
			<xsl:copy-of select="document('')/*/@xsi:schemaLocation"/>
			<xsl:apply-templates select="@* | node()" />
		</xsl:element>
	</xsl:template>
</xsl:stylesheet>
